name: Workflow_sequentiel

on:
  workflow_dispatch

env:
  a: 10
  b: 20

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: verification
        if: ${{ env.a > 0 && env.b > 0 }}
        run: |
          echo "le valeur de a est : $a"
          echo "le valeur de b est : $b"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executer l'application python
        run: python app.py
